### ISSUE TITLE
Can't log in with gnome-keyring 3.12

### ISSUE THREAD

**Issue by manjaro** [linuxmint/mdm#92] opened 2014-05-08 18:57 UTC
MDM seems not to work in Arch Linux and Manjaro with current packages. Using normal login with user name and password you will land on a grey screen with mouse pointer. This was tested with several DEs like Cinnamon, XFCE, KDE, Openbox in both distributions.

However: if you use autologin, it works. You will land on your desktop.

Can this be a permission issue with our custom used PAM files?

mdm.pam
<pre>#%PAM-1.0
auth            requisite       pam_nologin.so
auth            required        pam_env.so

auth            required        pam_unix.so
-auth		optional	pam_gnome_keyring.so

account         required        pam_unix.so

session         required        pam_limits.so
session         required        pam_unix.so
session         required        pam_systemd.so

password        required        pam_unix.so

-session	optional	pam_gnome_keyring.so auto_start</pre>

mdm-autologin.pam
<pre>#%PAM-1.0
auth            requisite       pam_nologin.so
auth            required        pam_env.so

auth            required        pam_permit.so

auth            sufficient      pam_succeed_if.so uid >= 1000 quiet
auth            required        pam_deny.so

account         required        pam_access.so
account         required        pam_time.so
account         required        pam_unix.so

password        required        pam_unix.so
password        required        pam_deny.so

session         required        pam_limits.so
session         required        pam_unix.so
session         required        pam_systemd.so

session         optional        pam_keyinit.so revoke
session         required        pam_limits.so
session         required        pam_unix.so</pre>

Any help on this issue is appreciated.

Se also issue #87

**Comment by monsta** [comment] 2015-01-20 09:52
Wait, but does that mean there are no "right" ./configure parameters when gnome-keyring is 3.12.x?

**Comment by clefebvre** [comment] 2015-03-04 09:04
Ok, I'm on this one as well. Here's what I found so far (working on Betsy):

- The problem doesn't occur on Betsy because at the moment it's missing libpam-gnome-keyring. Installing it re-creates the issue.
- I bissected gnome-keyring and I can confirm @ccasar 's findings: the regression is caused by https://github.com/GNOME/gnome-keyring/commit/2ca51a0aef5b1bc41f2e71d2b65edc8478dab69d

**Comment by clefebvre** [comment] 2015-03-05 12:18
The issue was in libpam-gnome-keyring. 

https://bugzilla.gnome.org/show_bug.cgi?id=745673

It's now fixed upstream.

https://github.com/GNOME/gnome-keyring/commit/a942c8f458e337d90101e6a81654478fda6ccfa9

**Closed by clefebvre** 2015-03-05 12:18 UTC
