### ISSUE TITLE
MDM fast user switch functionality became broken after kernel update

### ISSUE THREAD

**Issue by Kalevaxx** [linuxmint/mdm#178] opened 2016-07-17 15:32 UTC
O/S: Linux Mint Mate 18 amd64, kernel 4.4.0-28.
After installation of kernel 4.4.0-31-generic MDM fast user switching functionality stops to work. Removing of 4.4.0-31-generic kernel and all related packages (with apt-get purge) doesn't solve this issue.
Kernel (and all related stuff) was installed with update manager.
I've tried to enable verbose logging for MDM, but there are no usefull information what exactly was happened and why it can't start new instance of X.

**Comment by abdupattoh** [comment] 2016-11-29 00:53
This seems to be the same as cinnamon bug #5121 ?

I too have this bug and cannot find any logs to help me.

**Comment by abdupattoh** [comment] 2016-12-20 07:23
I just upgraded to Cinnamon 18.1 with hope... which was crushed when the bug still exists for me on multiple computers, one running 18, one running 18.1

I would be happy to find a log file to upload to help diagnose this, but I don't find any error output besides the dialog box that says "Cannot start new display  The X server failed.  Perhaps it is not configured well."


Switching to another virtual terminal, logging in as another user and typing startx seems to work on one machine to run a second cinnamon session for another user.  It did not work on my Linuxmint 18 machine though.  When I did it on the Linuxmint 18 machine, the main session was force-ably logged out.

**Comment by ACinnamonUserInUK** [comment] 2017-02-19 03:58
I wonder whether this is still a problem.

**Comment by abdupattoh** [comment] 2017-02-26 11:46
I just tried upgrading to 18.1 on my other machine.  Still a problem.

This is actually a bit of a pain when I want my family to share a machine at home.  Am I the only one with this use case, that I want multiple users on the same machine, and I hope to keep my kids on a more limited account?!

I would be happy to add more diagnostic info if told what direction to go.

**Comment by unixcrab** [comment] 2017-02-26 12:22
Affecting me too on a clean install of 18.1 with Cinnamon 3.2.7. Really irritating. I too can send logs if I know which ones.

**Comment by maphew** [comment] 2017-12-01 03:34
Affecting me too. Linux Mint 18.2.
Detailed version info: https://gist.github.com/anonymous/2d02753d0bec05b87d57c81a7769f875

Seems intermittent. User switching worked once earlier today but now not at all.

**Comment by xenopeek** [comment] 2018-01-28 13:40
I tried to reproduce this on Linux Mint 18.1 Cinnamon and I can switch to other users just fine. Perhaps I'm misunderstanding by with "**fast** user switching" you do mean "switch user" option from the logout dialog or user applet menu, right?

Linux Mint 18.1 was the last release that used MDM; subsequent releases use LightDM with our Slick Greeter, though MDM remains available for systems that have been upgraded in place.

**Comment by CottonEaster** [comment] 2018-01-28 15:11
I am sorry if I was unclear. Yes, I did indeed mean to refer to the 'switch user' option on the applet and logout menus.

If the issue cannot be reproduced on Mint 18.2+ (which uses LightDM), perhaps it should be closed. I will myself try to replicate the problem (on 18.3) later today.

**Comment by xenopeek** [comment] 2018-02-21 21:25
As there were no further updates I'm closing this issue.

**Closed by xenopeek** 2018-02-21 21:25 UTC
