### ISSUE TITLE
Wrong keyboard layout

### ISSUE THREAD

**Issue by callmemagnus** [linuxmint/mdm#5] opened 2012-08-02 06:10 UTC
hello,

as stated [here (french)](http://forums.linuxmint.com/viewtopic.php?f=63&t=107036) and [here](http://forums.linuxmint.com/viewtopic.php?f=205&t=100986) there seems to be an issue in the keyboard layout in MDM (and GDM) depending on some hardware configuration.

I want to be able to use my swiss french layout but it only provides me the US qwerty. 

I have: 
* logitech k750
* mint 13 cinnamon (problem appeared also present in Debian' unstable version of GDM)

I mention the keyboard as it seems that the issue was not there with my old USB keyboard.

I am willing to help testing if it does not break completely my setup (don't want to reinstall).

Should you need more information on my setup, don't hesitate to contact me.

EDIT:
I forgot to mention that except MDM (or GDM) the layout is the expected swiss french (console, after login...)

--
magnus

**Comment by clefebvre** [comment] 2016-04-20 17:11
It looks like the issue is in Xorg and it affects the Logitech Unified receiver. https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-evdev/+bug/995715

I'll try to get this fixed in Mint 18, either by:

- Forcing the layout in MDM (I need to test this, if it doesn't create regressions for other users, we can consider it)
- Detecting the presence of a keyboard connected via unified receiver and forcing the layout in MDM.

**Comment by clefebvre** [comment] 2016-05-05 16:26
Hi,

Sorry this took so long. It's great that we had a workaround in the meantime.

I was able to finally test a Mint 18 installation with an alpha ISO (please don't ask about this, they're not public), and I'm happy to confirm this issue is no longer present.

The test was done with an MK270 (Logitech wireless keyboard using unified receiver) and with a standard installation in French. Upon reboot, everything was using the French layout, including the login screen.

I can't say for sure whether this bug should be marked as fixed: https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-evdev/+bug/995715

But in any case, this issue was indeed upstream and it's fixed now.

**Closed by clefebvre** 2016-05-05 16:26 UTC
Labels: Planned

**Comment by clefebvre** [comment] 2016-11-15 16:13
I still can't reproduce this issue, despite some people telling me it's still there in Mint 18... 

This commit explicitly sets the layout:

https://github.com/linuxmint/mdm/commit/a293167340624021e1b379118a647a97da9dd550

**Comment by artem-sidorenko** [comment] 2016-11-19 13:12
@clefebvre I see this behavior and can reproduce it:
 - I have X220 with docking station and logitech K520/M310 connected to the docking station. Its Mint 18 with cinnamon
 - I boot the system in the docked state and I get a login prompt of MDM
 - If I do not touch the notebook keyboard but use logitech keyboard -> I get wrong keyboard layout (US instead of DE in my case)
 - If I hit at least one key on the notebook keyboard -> the layout switches automatically to the right layout (DE in my case). Logitech keyboard uses the proper layout after this as well

**Comment by naimdjon** [comment] 2017-01-30 13:17
I have a similar issue (in Mint 17), using K750. I have the correct layout for some time, and after a while, it switches to US layout automatically. I noticed it happens even if I don't press anything. 

The workaround is manually setting the layout in the init script.
