### ISSUE TITLE
Mint 17.2 MDM: Stuck logging into MATE when switching sessions from MATE to Cinnamon

### ISSUE THREAD

**Issue by wereturtle** [linuxmint/mdm#155] opened 2015-09-22 18:31 UTC
I am having a problem switching between MATE and Cinnamon sessions from MDM.  It ended up to where it would only let me into MATE.  What happened was that I would log out from Cinnamon, use MDM to switch to MATE, and log in.  It would strangely ask me to log in (i.e., enter my password) twice, sometimes without my MDM login theme showing up (just a plain login dialog).  I think that it was falling back to x-session-manager.  Falling back to the x-session-manager seems to be sporadic.  Regardless, I would have to be sure to select MATE as my session again before entering my password a second time, or else I'd end up back in Cinnamon.

After playing around in MATE for a while, I tried getting back into Cinnamon the same way.  At first, there were the same symptoms.  Eventually, after switching back and forth between MATE and Cinnamon several times, I couldn't get into Cinnamon anymore.  It just kept booting me into MATE, even when I set Cinnamon to be the default session from the Login Window Preferences.

I found out that the .dmrc file was set to MATE.  I was able to get back into Cinnamon by manually changing the .dmrc file to point to Cinnamon before logging out of MATE.  If I log into MATE again, the .dmrc file will be changed again to MATE, and I'll have to modify it yet again if I want back into Cinnamon.

Is there a more permanent workaround for this?

Thanks!

**Comment by zorbama** [comment] 2015-10-16 13:41
I have the same issue. It happened to me when switching between KDE and Cinnamon and between Cinnamon and XFCE, so it's safe to assume that whatever is decided as the default environment is fixed that way.

**Comment by wereturtle** [comment] 2016-03-27 17:23
Just as a followup:

I found that if you use the GTK theme in MDM, you'll be able to switch between MATE and Cinnamon with no issues.  However, if, for example, your default session is Cinnamon, and you switch to MATE, and then log out and then leave it set to the default session and try to log back in, it still boots you back to MATE.  You have to switch to, say, the Cinnamon Software Rendering session to get back into Cinnamon.  So basically, once you leave the 3D Cinnamon, if it's your default session, you can't get back in without fixing the .dmrc file yet again.

GDM themes seem to behave even worse.  They won't switch sessions at all the first time, and might the second time, falling back to the GTK theme at random.  Then you get stuck again.  I've had several times where a GDM theme, when attempting to switch the session, left me with a black screen and a mouse pointer.

HTML themes behave slightly better than the GDM themes, but still exhibit strange behavior.  If you're using an HTML theme after using the GTK theme, it will probably mostly work as well as the GTK theme, but if you use and HTML theme after having used a GDM theme, it begins to behave as badly as the GDM theme.

It ultimately comes down to the .dmrc file.  It's not being consistently updated like it should be.  In fact, using the Login Window GUI in Cinnamon to set the default theme doesn't work.  The .dmrc file is never updated with the default theme, and it seems that all the login themes go off this one file.

**Comment by xenopeek** [comment] 2018-01-28 11:44
This issue happens only if a user has set "Default session" in Login Window > Options to something other than "Automatically detected". With it set to automatically detected the default session is the last used one and switching sessions works as intended.

If another session is specific as default on Login Windows > Options, this issue occurs. I tried it on Linux Mint 18.1 Cinnamon with mint-meta-xfce added, MDM theme set to GTK and the default session set to Cinnamon instead of automatically detected. Logging out and switching to Xfce works but to be able to get back to Cinnamon I needed to use the Cinnamon (Software Rendering) session as using either Default or Cinnamon instead gave me Xfce again.

**Comment by xenopeek** [comment] 2018-02-21 20:37
We would welcome a PR to improve handling of default session when not set to automatically detected (in which this issue doesn't occur) but as this issue isn't preventing MDM from working and Linux Mint has moved to use LightDM I'm closing this issue.

**Closed by xenopeek** 2018-02-21 20:37 UTC
